13 maj 2019 15:28:28
, Exception has been thrown: The Item Id: 3661 cannot be found
se.kth.iv1350.pos.dbhandler.InvalidIDException: The Item Id: 3661 cannot be found
	at se.kth.iv1350.pos.dbhandler.Inventory.checkValidation(Inventory.java:46)
	at se.kth.iv1350.pos.controller.Controller.addItem(Controller.java:53)
	at se.kth.iv1350.pos.view.View.addItem(View.java:98)
	at se.kth.iv1350.pos.view.View.runFakeSale(View.java:61)
	at se.kth.iv1350.pos.startUp.Main.main(Main.java:31)
13 maj 2019 15:28:32
, Exception has been thrown: There is no connection to database
se.kth.iv1350.pos.dbhandler.ConnectionFailureException: There is no connection to database
	at se.kth.iv1350.pos.dbhandler.Inventory.checkValidation(Inventory.java:38)
	at se.kth.iv1350.pos.controller.Controller.addItem(Controller.java:53)
	at se.kth.iv1350.pos.view.View.addItem(View.java:98)
	at se.kth.iv1350.pos.view.View.runFakeSale(View.java:61)
	at se.kth.iv1350.pos.startUp.Main.main(Main.java:31)
